Set FontSize 20
Set Width 1600
Set Height 800
Set Framerate 30
Set Padding 12

Output gifs/demo.gif

Hide
Type@10ms "puffin -file data/hledger.journal"
Enter
Sleep 2s

Show

Sleep 2s

Set TypingSpeed 500ms

Type "m"
Sleep 2s
Type "y"

Sleep 2s

Down
Sleep 2s
Down
Sleep 2s
Down
Sleep 2s
Down
Sleep 2s
Down
Sleep 2s
Down

Sleep 2s
Type "f"
Type "assets"
Enter
Sleep 2s

Down
Type "2022-05-01"
Enter
Sleep 2s
